import {ProjectProps} from 'components';

import {PROJECT_URL} from 'constants/string';

const projects: ProjectProps[] = [
  {
    name: 'BUDGET MANAGER',
    image: PROJECT_URL('budget-manager'),
    descriptions:
      'IS A MOBILE WEB APPLICATION HELPING TOOL SERVICE WHICH CAN HANDLE LIST OF BUDGET YOU THAT THE USER HAVE, INSIDE OF EACH BUDGET THERE IS NUMBER OF ITEMS WITH AN AUTOMATED COMPUTATION PRICE AND CAN EASILY COMPARE THEIR POSSIBLE BUDGET PLANS.',
    tags: ['MOBILE WEB APPLICATION', 'REACT-JS', 'FLAKS-API', 'POSTGRESQL']
  },
  {
    name: 'BROOWING COFFEE',
    image: PROJECT_URL('broowing-coffee'),
    descriptions:
      'IS A MOBILE WEB POINT OF SALE AND INVENTORY MANAGEMENT WITH A REAL LIFE DESIGN SCENARIO, CREATE PRODUCT, INCLUDE THE INVENTORY, CREATE TRANSACTION WITH AN E-RECEIPT AT THE SAME TIME THE DEDUCTION OF INVENTORY SIMULTENEOUSLY, AND YES IT CAN ALSO CREATE A REPORTS.',
    tags: ['MOBILE WEB APPLICATION', 'REACT-JS', 'EXPRESS-API', 'MONGODB']
  },
  // {
  //   name: 'OUR-CHAT',
  //   image: projectOurChat,
  //   descriptions:
  //     'IS A MOBILE OR DESKTOP WEB APPLICATION WHEREIN YOU CAN INTERACT RANDOM PEOPLES, THERE IS A SEARCHING FEATURES TO THOSE USERS UP FOR SESSION WITH FEATURE THAT CAN FILTER USERS, BASE ON GENDER, IT CAN CREATE PRIVATE CONVERSATION GROUP OF PEOPLE AND IT HAS A GLOBAL COMMUNITY WITH MAXIMUM OF 10 USERS.',
  //   tags: [
  //     'WEB APPLICATION',
  //     'MOBILE APPLICATION',
  //     'REACT-JS',
  //     'EXPRESS-JS',
  //     'EXPRESS-LOCALS',
  //   ],
  // },
  {
    name: 'ROCKET PAPER SCISSOR',
    image: PROJECT_URL('rps'),
    descriptions:
      'IS A 2D ANDROID MOBILE ONLINE GAME THAT GIVES AN INTERACTIVE TO USERS, WHEN THE GAME START THE USER SHOULD CHOOSE WHAT BATTLE HAND THAT USER USE, AND VALIDATE THE BATTLE WHO IS WINNER.',
    tags: ['ANDROID APPLICATION', 'REACT-NATIVE', 'EXPRESS-JS', 'MONGODB']
  }
];

export default projects;
