name: 'deployment'
run-name: 'build and deploy'
on:
  push:
    branches:
      - release/2.0.0
jobs:
  build_and_deploy:
    name: 'build'
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.ACC3SS_T0K3N }}

      - name: build
        run: |
          - npm install
          - npm run build
